### ISSUE TITLE
如何在Linux Arm64上编译

### ISSUE THREAD

**Issue by Z-fly** [tonquer/waifu2x-vulkan#10]
src/waifu2x_py.cpp:46:16: note: ‘sprintf’ output between 5 and 260 bytes into a destination of size 256
         46 |         sprintf(modelNameTTa, "%s_TTA", modelName);
            |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      aarch64-linux-gnu-g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-aarch64-cpython-311/src/waifu2x.o build/temp.linux-aarch64-cpython-311/src/waifu2x_main.o build/temp.linux-aarch64-cpython-311/src/waifu2x_py.o build/temp//ncnntmp/src/libncnn.a build/temp//webptmp/libwebp.a build/temp//webptmp/libwebpmux.a build/temp//webptmp/libwebpdemux.a build/temp//pngtmp/libpng.a build/temp//pngtmp/zlib/libz.a VulkanSDK/linux/libvulkan.so build/temp//ncnntmp/glslang/SPIRV/libSPIRV.a build/temp//ncnntmp/glslang/glslang/libglslang.a build/temp//ncnntmp/glslang/glslang/libMachineIndependent.a build/temp//ncnntmp/glslang/OGLCompilersDLL/libOGLCompiler.a build/temp//ncnntmp/glslang/glslang/OSDependent/Unix/libOSDependent.a build/temp//ncnntmp/glslang/glslang/libGenericCodeGen.a -L/usr/lib/aarch64-linux-gnu -lgomp -o build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/waifu2x_vulkan.cpython-311-aarch64-linux-gnu.so -fopenmp
      /usr/bin/ld: VulkanSDK/linux/libvulkan.so: error adding symbols: file in wrong format
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/aarch64-linux-gnu-g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for waifu2x-vulkan
Failed to build waifu2x-vulkan

**Comment by Z-fly** [comment]
![image](https://github.com/tonquer/waifu2x-vulkan/assets/10470892/08855cca-0a7d-42ee-99c8-1cb0723889ba)

**Comment by tonquer** [comment]
你需要先编译一个arm的vulkan库，替换VulkanSDK/linux/libvulkan.so

**Comment by Z-fly** [comment]
能否用这种方法？https://zhuanlan.zhihu.com/p/663627551

**Comment by tonquer** [comment]
你用apt安装libvulkan1，然后找到安装后的libvulkan.so.1替换VulkanSDK/linux/libvulkan.so
再在目录用python setup.py bdist_wheel编译试试

**Comment by Z-fly** [comment]
(venv) root@debian:~/waifu2x-vulkan# python setup.py bdist_wheel
linux
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-aarch64-cpython-311
creating build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
copying waifu2x_vulkan/hook-waifu2x_vulkan.py -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
copying waifu2x_vulkan/waifu2x.py -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
copying waifu2x_vulkan/__init__.py -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
running egg_info
creating waifu2x_vulkan.egg-info
writing waifu2x_vulkan.egg-info/PKG-INFO
writing dependency_links to waifu2x_vulkan.egg-info/dependency_links.txt
writing entry points to waifu2x_vulkan.egg-info/entry_points.txt
writing top-level names to waifu2x_vulkan.egg-info/top_level.txt
writing manifest file 'waifu2x_vulkan.egg-info/SOURCES.txt'
reading manifest file 'waifu2x_vulkan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pyd' under directory 'waifu2x_vulkan'
warning: no files found matching '*.so' under directory 'waifu2x_vulkan'
adding license file 'LICENSE'
writing manifest file 'waifu2x_vulkan.egg-info/SOURCES.txt'
/root/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'waifu2x_vulkan.models' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'waifu2x_vulkan.models' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'waifu2x_vulkan.models' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'waifu2x_vulkan.models' to be distributed and are
        already explicitly excluding 'waifu2x_vulkan.models' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
copying waifu2x_vulkan/hook-waifu2x_vulkan.py -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
copying waifu2x_vulkan/waifu2x_vulkan.pyi -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan
creating build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models
creating build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise0_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise0_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise0_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise0_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise1_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise1_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise1_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise1_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise2_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise2_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise2_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise2_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise3_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise3_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise3_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/noise3_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
copying waifu2x_vulkan/models/models-cunet/scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-cunet
creating build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise0_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise0_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise1_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise1_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise2_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise2_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise3_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise3_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
copying waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb
creating build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise0_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise0_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise1_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise1_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise2_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise2_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise3_scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/noise3_scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/scale2.0x_model.bin -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
copying waifu2x_vulkan/models/models-upconv_7_photo/scale2.0x_model.param -> build/lib.linux-aarch64-cpython-311/waifu2x_vulkan/models/models-upconv_7_photo
running build_ext
-- The C compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success
-- Symbol prefix: 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/waifu2x-vulkan/build/temp/pngtmp
[  1%] Generating pnglibconf.c
[  2%] Generating pnglibconf.out
[  3%] Generating pnglibconf.h
[  5%] Generating scripts/sym.out
[  6%] Generating libpng.sym
[  7%] Generating scripts/vers.out
[  9%] Generating libpng.vers
[ 10%] Generating pngprefix.h
[ 11%] Generating scripts/intprefix.out
[ 12%] Generating scripts/pnglibconf.c
[ 14%] Generating scripts/prefix.out
[ 15%] Generating scripts/symbols.out
[ 16%] Generating scripts/symbols.chk
[ 16%] Built target genfiles
[ 18%] Building C object zlib/CMakeFiles/zlibstatic.dir/adler32.o
[ 19%] Building C object zlib/CMakeFiles/zlibstatic.dir/compress.o
[ 20%] Building C object zlib/CMakeFiles/zlibstatic.dir/crc32.o
[ 22%] Building C object zlib/CMakeFiles/zlibstatic.dir/deflate.o
[ 23%] Building C object zlib/CMakeFiles/zlibstatic.dir/gzclose.o
[ 24%] Building C object zlib/CMakeFiles/zlibstatic.dir/gzlib.o
[ 25%] Building C object zlib/CMakeFiles/zlibstatic.dir/gzread.o
[ 27%] Building C object zlib/CMakeFiles/zlibstatic.dir/gzwrite.o
[ 28%] Building C object zlib/CMakeFiles/zlibstatic.dir/inflate.o
[ 29%] Building C object zlib/CMakeFiles/zlibstatic.dir/infback.o
[ 31%] Building C object zlib/CMakeFiles/zlibstatic.dir/inftrees.o
[ 32%] Building C object zlib/CMakeFiles/zlibstatic.dir/inffast.o
[ 33%] Building C object zlib/CMakeFiles/zlibstatic.dir/trees.o
[ 35%] Building C object zlib/CMakeFiles/zlibstatic.dir/uncompr.o
[ 36%] Building C object zlib/CMakeFiles/zlibstatic.dir/zutil.o
[ 37%] Linking C static library libz.a
[ 37%] Built target zlibstatic
[ 38%] Building C object CMakeFiles/png_static.dir/png.c.o
[ 40%] Building C object CMakeFiles/png_static.dir/pngerror.c.o
[ 41%] Building C object CMakeFiles/png_static.dir/pngget.c.o
[ 42%] Building C object CMakeFiles/png_static.dir/pngmem.c.o
[ 44%] Building C object CMakeFiles/png_static.dir/pngpread.c.o
[ 45%] Building C object CMakeFiles/png_static.dir/pngread.c.o
[ 46%] Building C object CMakeFiles/png_static.dir/pngrio.c.o
[ 48%] Building C object CMakeFiles/png_static.dir/pngrtran.c.o
[ 49%] Building C object CMakeFiles/png_static.dir/pngrutil.c.o
[ 50%] Building C object CMakeFiles/png_static.dir/pngset.c.o
[ 51%] Building C object CMakeFiles/png_static.dir/pngtrans.c.o
[ 53%] Building C object CMakeFiles/png_static.dir/pngwio.c.o
[ 54%] Building C object CMakeFiles/png_static.dir/pngwrite.c.o
[ 55%] Building C object CMakeFiles/png_static.dir/pngwtran.c.o
[ 57%] Building C object CMakeFiles/png_static.dir/pngwutil.c.o
[ 58%] Building C object CMakeFiles/png_static.dir/arm/arm_init.c.o
[ 59%] Building ASM object CMakeFiles/png_static.dir/arm/filter_neon.S.o
[ 61%] Building C object CMakeFiles/png_static.dir/arm/filter_neon_intrinsics.c.o
[ 62%] Building C object CMakeFiles/png_static.dir/arm/palette_neon_intrinsics.c.o
[ 63%] Linking C static library libpng16.a
[ 68%] Built target png_static
[ 70%] Building C object zlib/CMakeFiles/zlib.dir/adler32.o
[ 71%] Building C object zlib/CMakeFiles/zlib.dir/compress.o
[ 72%] Building C object zlib/CMakeFiles/zlib.dir/crc32.o
[ 74%] Building C object zlib/CMakeFiles/zlib.dir/deflate.o
[ 75%] Building C object zlib/CMakeFiles/zlib.dir/gzclose.o
[ 76%] Building C object zlib/CMakeFiles/zlib.dir/gzlib.o
[ 77%] Building C object zlib/CMakeFiles/zlib.dir/gzread.o
[ 79%] Building C object zlib/CMakeFiles/zlib.dir/gzwrite.o
[ 80%] Building C object zlib/CMakeFiles/zlib.dir/inflate.o
[ 81%] Building C object zlib/CMakeFiles/zlib.dir/infback.o
[ 83%] Building C object zlib/CMakeFiles/zlib.dir/inftrees.o
[ 84%] Building C object zlib/CMakeFiles/zlib.dir/inffast.o
[ 85%] Building C object zlib/CMakeFiles/zlib.dir/trees.o
[ 87%] Building C object zlib/CMakeFiles/zlib.dir/uncompr.o
[ 88%] Building C object zlib/CMakeFiles/zlib.dir/zutil.o
[ 89%] Linking C shared library libz.so
[ 89%] Built target zlib
[ 90%] Building C object zlib/CMakeFiles/example.dir/test/example.o
[ 92%] Linking C executable example
[ 92%] Built target example
[ 93%] Building C object zlib/CMakeFiles/minigzip.dir/test/minigzip.o
[ 94%] Linking C executable minigzip
[ 94%] Built target minigzip
[ 96%] Building C object zlib/CMakeFiles/example64.dir/test/example.o
[ 97%] Linking C executable example64
[ 97%] Built target example64
[ 98%] Building C object zlib/CMakeFiles/minigzip64.dir/test/minigzip.o
[100%] Linking C executable minigzip64
[100%] Built target minigzip64
CMake Warning:
  Ignoring extra path from command line:

   "/root/waifu2x-vulkan/src/libwebp"


CMake Error: The source directory "/root/waifu2x-vulkan/src/libwebp" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/root/waifu2x-vulkan/setup.py", line 293, in <module>
    setuptools.setup(
  File "/root/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/venv/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 369, in run
    self.run_command("build")
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/venv/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/venv/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/root/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/waifu2x-vulkan/setup.py", line 251, in build_extension
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/root/waifu2x-vulkan/src/libwebp', '-DWEBP_ENABLE_SIMD=ON', '-DWEBP_BUILD_ANIM_UTILS=OFF', '-DWEBP_BUILD_CWEBP=OFF', '-DWEBP_BUILD_DWEBP=OFF', '-DWEBP_BUILD_GIF2WEBP=OFF', '-DWEBP_BUILD_IMG2WEBP=OFF', '-DWEBP_BUILD_VWEBP=OFF', '-DWEBP_BUILD_WEBPINFO=OFF', '-DWEBP_BUILD_WEBPMUX=OFF', '-DWEBP_BUILD_EXTRAS=OFF', '-DWEBP_BUILD_WEBP_JS=OFF', '-DWEBP_NEAR_LOSSLESS=OFF', '-DWEBP_ENABLE_SWAP_16BIT_CSP=OFF']' returned non-zero exit status 1.
